base:
    app_chain_type: opb # application chain type
    store_path: .db # store path
    http_port: 8082

# irita-hub config
hub:
    chain_id: wenchangchain
    node_rpc_addr: http://10.1.4.149:36657
    node_grpc_addr: 10.1.4.149:39090
    account:
        key_name: node0
        passphrase: 12345678
        key_armor: "-----BEGIN TENDERMINT PRIVATE KEY-----\nkdf: bcrypt\nsalt: E82064503E284EE753B13E9424B08B4C\ntype: sm2\n\nqLgix+DPFfNY+TpWWlNmquy3jUDR314/dJmIxw8JCWGiSn4deFtp8IWGH/mnVe6S\nNdGt6OJ2SbwO098fk16Gw6RO+MgVjShVMXbkggc=\n=h7AT\n-----END TENDERMINT PRIVATE KEY-----"
    fee: 400000upoint
# opb config
opb:
    chain_id: wenchangchain
    rpc_addrs:
        opb1.bsnbase.com: http://10.1.4.149:36657
    grpc_addrs:
        opb1.bsnbase.com: 10.1.4.149:39090
    account:
        key_name: node1
        passphrase: 12345678
        key_armor: "-----BEGIN TENDERMINT PRIVATE KEY-----\nkdf: bcrypt\nsalt: E82064503E284EE753B13E9424B08B4C\ntype: sm2\n\nqLgix+DPFfNY+TpWWlNmquy3jUDR314/dJmIxw8JCWGiSn4deFtp8IWGH/mnVe6S\nNdGt6OJ2SbwO098fk16Gw6RO+MgVjShVMXbkggc=\n=h7AT\n-----END TENDERMINT PRIVATE KEY-----"
    default_fee: 2000000upoint
    default_gas: 500000
    monitor_interval: 1 # chain monitoring interval in seconds
    timeout: 20

# mysql config
mysql:
    db_name: relayer
    db_user_name: root
    db_user_passphrase: 123456
    host: localhost
    port: 3306

# service config
service:
    service_name: cc-contract-call
    schemas:  '{"input":{"type":"object"},"output":{"type:"object"}}'
    provider: iaa13fnhnwmjmkdf9wdy3f3ee0umfve8hyarwaerqm
    service_fee:
    timeout: 20
    qos: 1001000000upoint