base:
    app_chain_type: opb # application chain type
    store_path: .db # store path
    http_port: 8082

# irita-hub config
hub:
    chain_id: irita
    node_rpc_addr: http://127.0.0.1:26657
    node_grpc_addr: 127.0.0.1:9090
    key_path: .keys
    key_name: node0
    passphrase: 1234567890

# opb config
opb:
    chain_id: test
    rpc_addrs:
        opb1.bsnbase.com: http://127.0.0.1:26658
    grpc_addrs:
        opb1.bsnbase.com: 127.0.0.1:9091
    key_path: .keys
    key_name: node1
    passphrase: 1234567890
    default_fee: 2000000uirita
    monitor_interval: 1 # chain monitoring interval in seconds
    timeout: 20

# mysql config
mysql:
    db_name: relayer
    db_user_name: root
    db_user_passphrase: 123456
    host: localhost
    port: 3306

# service config
service:
    service_name: cc-contract-call
    schemas:  '{"input":{"type":"object"},"output":{"type:"object"}}'
    provider: iaa1fe6gm5kyam6xfs0wngw3d23l9djlyw82xxcjm2
    service_fee: 1000000upoint
    timeout: 20
    qos: 100