base:
    app_chain_type: opb # application chain type
    store_path: .db # store path
    http_port: 8082

# irita-hub config
hub:
    chain_id: wenchangchain
    node_rpc_addr: http://10.1.4.149:36657
    node_grpc_addr: 10.1.4.149:39090
    key_mode: file
    key_path: .keys
    key_name: node0
    passphrase: 12345678
#    key_armor: ""


# opb config
opb:
    chain_id: wenchangchain
    rpc_addrs:
        opb1.bsnbase.com: http://10.1.4.149:36657
    grpc_addrs:
        opb1.bsnbase.com: 10.1.4.149:39090
    key_mode: file
    key_path: .keys
    key_name: node1
    passphrase: 12345678
#    key_armor: ""
    default_fee: 2000000upoint
    default_gas: 5000000
    monitor_interval: 1 # chain monitoring interval in seconds
    timeout: 20

# mysql config
mysql:
    db_name: relayer
    db_user_name: root
    db_user_passphrase: 123456
    host: localhost
    port: 3306

# service config
service:
    service_name: cc-contract-call
    schemas:  '{"input":{"type":"object"},"output":{"type:"object"}}'
    provider: iaa13fnhnwmjmkdf9wdy3f3ee0umfve8hyarwaerqm
    service_fee:
    timeout: 20
    qos: 100