base:
    # application chain name
    app_chain_name: eth

# irita-hub config
hub:
    chain_id: irita-hub
    node_rpc_addr: http://127.0.0.1:26657
    key: node0
    passphrase: 1234567890
    db_root: .data/hub

# ethereum config
eth:
    chain_id: ropsten
    node_rpc_addr: ws://127.0.0.1:8546
    IServiceCoreContract: 0x6dc3d7d44c3ce74c2a1af2d66ed4ac2093ded5e4
    IServiceMarketContract: 0x1799681bdbfed2c9d38d74d6781001c0677efb86
    key: test
    passphrase: 1234567890

# fabric config
fabric:
    channel_id: test-channel
    peer_rpc_addrs:
      - grpc://127.0.0.1:7051
      - grpc://127.0.0.1:7052
    orderer_rpc_addr: grpc://127.0.0.1:7050
    key: test
    passphrase: 1234567890
