# application chain name
app_chain_name: fabric

# fabric config
fabric:
    channel_id: test
    peer_rpc_addrs:
      - 192.168.0.1
      - 192.168.0.2
    orderer_rpc_addr: 127.0.0.1
    key: test
    passphrase: 1234567890

# hub config
hub:
    chain_id: irita-hub
    node_rpc_addr: 127.0.0.1
    key: node0
    passphrase: 1234567890