base:
    app_chain_type: eth # application chain type
    store_path: .db # store path
    http_port: 8082

# irita-hub config
hub:
    chain_id: irita
    node_rpc_addr: http://127.0.0.1:26657
    node_grpc_addr: 127.0.0.1:9090
    key_path: .keys
    key_name: node0
    passphrase: 1234567890

# ethereum config
eth:
    chain_id: ropsten
    gas_limit: 2000000
    gas_price: 5000000000
    key: 45760456b8181a0c3a313e8d9031b1f9343b1f45baaf5043262c19b63b163d5f
    passphrase: wd941014
    iservice_event_name: CrossChainRequestSent
    iservice_event_sig: CrossChainRequestSent(bytes32,string,string,bytes,address)
    nodes:
        eth1.bsnbase.com: wss://ropsten.infura.io/ws/v3/56e89587eacb4fbe8655e4c44b146237

# mysql config
mysql:
    db_name: relayer
    db_user_name: root
    db_user_passphrase: 123456
    host: localhost
    port: 3306

# service config
service:
    service_name: cc-contract-call
    schemas:  '{"input":{"type":"object"},"output":{"type:"object"}}'
    provider: iaa15s9sulrnmctzluc42g7lkxh92ardkc9xccxsy9
    service_fee: 1000000upoint
    qos: 100